### ISSUE TITLE
Initializing Frontend

### ISSUE THREAD

**Issue by mingmurray** [COSC481W-2024Fall/OurSpace#8]
Initialize Frontend

**User Story:**

Bob wants to be able to access the URL for OurSpace.

User: Bob who wants to access OurSpace.
Feature: URL that opens up our website to our prototype home page
Business Value: If home page is created, the user will easily be able to navigate through posts and other tabs

**Tasks:**

Create HTML that will potentially be our homepage
Add our prototype logo on the top of the screen to show progress
Create CSS that will potentially be the way we design our webpage
Add a bit of design to show progress

**Acceptance Tests**

- [ ] Able to access website without difficulty
- [ ] CSS file is connected to our HTML and is working properly
- [ ] Can see logo

**Acceptance Criteria**

1. Can see designs we implemented
2. Can see logo we added
